### PR TITLE
Co-vendor array-api-compat

### PR DESCRIPTION
**Pull request by crusaderky**
untested

### CODE REVIEW

**Comment by lucascolley** [comment]
thanks @crusaderky, this looks great! I see one problem:

```
(sklearn-env) lucascolley@Lucass-MacBook-Air-5 scikit-learn % pytest sklearn/linear_model
ImportError while loading conftest '/Users/lucascolley/programming/scikit-learn/sklearn/conftest.py'.
sklearn/conftest.py:32: in <module>
    from sklearn.utils._testing import get_pytest_filterwarning_lines
sklearn/utils/_testing.py:318: in <module>
    _check_array_api_dispatch(True)
sklearn/utils/_array_api.py:118: in _check_array_api_dispatch
    raise RuntimeError(
E   RuntimeError: Scikit-learn array API support was enabled but scipy's own support is not enabled. Please set the SCIPY_ARRAY_API=1 environment variable before importing sklearn or scipy. More details at: https://docs.scipy.org/doc/scipy/dev/api-dev/array_api.html
```

I think previously, scikit-learn's Array API support being enabled was determined by whether array-api-compat was installed. Now that it is vendored, I think we'll need a different way to opt in (maybe an env var `SKLEARN_ARRAY_API` like SciPy has).

**Comment by crusaderky** [comment]
is there any benefit in having a separate variable? To me it would make a lot more sense to piggyback on scipy's variable.

**Comment by lucascolley** [comment]
good point, looks like the failure was just https://github.com/scikit-learn/scikit-learn/pull/30340/commits/1353b8523fa4c33a49fb21b5f0006b2ba705d942

**Comment by lucascolley** [comment]
thanks!

**Pull request merged**
